import { classifyTool } from './environments';
import type {
  Implementation,
  Prompt,
  Resource,
  ResourceTemplate,
  ServerCapabilities,
  Tool,
} from './protocol';
import { normalizeSchema, type FieldSpec } from './schema';
import { sampleObject } from './testgen';

export interface DocsInput {
  name: string;
  serverInfo?: Implementation;
  protocolVersion?: string;
  instructions?: string;
  capabilities?: ServerCapabilities;
  tools: Tool[];
  resources: Resource[];
  resourceTemplates: ResourceTemplate[];
  prompts: Prompt[];
}

/**
 * Generates Markdown from the *live* catalog rather than from source, so the
 * documentation cannot drift from what the server actually advertises. Examples
 * are built from the same schema sampler the test generator uses.
 */
export function generateDocs(input: DocsInput): string {
  const lines: string[] = [];

  lines.push(`# ${input.name}`, '');
  if (input.serverInfo) {
    lines.push(
      `\`${input.serverInfo.name}\` v${input.serverInfo.version}` +
        (input.protocolVersion ? ` · MCP protocol \`${input.protocolVersion}\`` : ''),
      '',
    );
  }
  if (input.instructions) {
    lines.push(input.instructions, '');
  }

  lines.push('> Generated by MCPilot from the running server.', '');

  // Contents
  lines.push('## Contents', '');
  if (input.tools.length) {
    lines.push('- [Tools](#tools)');
  }
  if (input.resources.length || input.resourceTemplates.length) {
    lines.push('- [Resources](#resources)');
  }
  if (input.prompts.length) {
    lines.push('- [Prompts](#prompts)');
  }
  lines.push('- [Capabilities](#capabilities)', '');

  // Tools
  if (input.tools.length) {
    lines.push('## Tools', '');
    lines.push('| Tool | Risk | Summary |', '| --- | --- | --- |');
    for (const tool of input.tools) {
      lines.push(
        `| [\`${tool.name}\`](#${anchor(tool.name)}) | ${classifyTool(tool)} | ${
          firstLine(tool.description) || '—'
        } |`,
      );
    }
    lines.push('');

    for (const tool of input.tools) {
      lines.push(...documentTool(tool));
    }
  }

  // Resources
  if (input.resources.length || input.resourceTemplates.length) {
    lines.push('## Resources', '');
    for (const resource of input.resources) {
      lines.push(`### \`${resource.uri}\``, '');
      if (resource.description) {
        lines.push(resource.description, '');
      }
      lines.push(
        `- Name: \`${resource.name}\``,
        `- MIME type: ${resource.mimeType ? `\`${resource.mimeType}\`` : '_not declared_'}`,
        '',
      );
    }
    for (const template of input.resourceTemplates) {
      lines.push(`### \`${template.uriTemplate}\` (template)`, '');
      if (template.description) {
        lines.push(template.description, '');
      }
    }
  }

  // Prompts
  if (input.prompts.length) {
    lines.push('## Prompts', '');
    for (const prompt of input.prompts) {
      lines.push(`### \`${prompt.name}\``, '');
      if (prompt.description) {
        lines.push(prompt.description, '');
      }
      if (prompt.arguments?.length) {
        lines.push('| Argument | Required | Description |', '| --- | --- | --- |');
        for (const argument of prompt.arguments) {
          lines.push(
            `| \`${argument.name}\` | ${argument.required ? 'yes' : 'no'} | ${
              argument.description ?? '—'
            } |`,
          );
        }
        lines.push('');
      } else {
        lines.push('_No arguments._', '');
      }
    }
  }

  // Capabilities
  lines.push('## Capabilities', '');
  lines.push('```json', JSON.stringify(input.capabilities ?? {}, null, 2), '```', '');

  return lines.join('\n');
}

function documentTool(tool: Tool): string[] {
  const lines: string[] = [];
  const spec = normalizeSchema(tool.inputSchema);
  const risk = classifyTool(tool);

  lines.push(`### \`${tool.name}\``, '');
  if (risk === 'destructive') {
    lines.push('> ⚠️ **Destructive.** This tool may change or delete data.', '');
  }
  if (tool.description) {
    lines.push(tool.description, '');
  }

  const children = spec.children ?? [];
  if (children.length) {
    lines.push('**Parameters**', '');
    lines.push('| Name | Type | Required | Description |', '| --- | --- | --- | --- |');
    for (const child of children) {
      lines.push(
        `| \`${child.name}\` | ${typeLabel(child)} | ${child.required ? 'yes' : 'no'} | ${
          describeField(child) || '—'
        } |`,
      );
    }
    lines.push('');
  } else {
    lines.push('_Takes no parameters._', '');
  }

  lines.push('**Example**', '', '```json', JSON.stringify(sampleObject(spec), null, 2), '```', '');

  if (tool.outputSchema) {
    lines.push(
      '<details><summary>Output schema</summary>',
      '',
      '```json',
      JSON.stringify(tool.outputSchema, null, 2),
      '```',
      '',
      '</details>',
      '',
    );
  }

  return lines;
}

function typeLabel(spec: FieldSpec): string {
  if (spec.kind === 'enum') {
    const values = (spec.enumValues ?? []).map((v) => `\`${String(v)}\``).join(' \\| ');
    return values || 'enum';
  }
  if (spec.kind === 'array') {
    return `${spec.item ? spec.item.kind : 'any'}[]`;
  }
  return spec.nullable ? `${spec.kind}?` : spec.kind;
}

function describeField(spec: FieldSpec): string {
  const parts: string[] = [];
  if (spec.description) {
    parts.push(spec.description.replace(/\n/g, ' '));
  }
  const constraints: string[] = [];
  if (spec.format) {
    constraints.push(`format \`${spec.format}\``);
  }
  if (spec.constraints.minimum !== undefined) {
    constraints.push(`min ${spec.constraints.minimum}`);
  }
  if (spec.constraints.maximum !== undefined) {
    constraints.push(`max ${spec.constraints.maximum}`);
  }
  if (spec.constraints.minLength !== undefined) {
    constraints.push(`minLength ${spec.constraints.minLength}`);
  }
  if (spec.defaultValue !== undefined) {
    constraints.push(`default \`${JSON.stringify(spec.defaultValue)}\``);
  }
  if (constraints.length) {
    parts.push(`(${constraints.join(', ')})`);
  }
  return parts.join(' ');
}

function anchor(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '');
}

function firstLine(value?: string): string {
  if (!value) {
    return '';
  }
  const line = value.split('\n')[0].trim();
  return line.length > 100 ? `${line.slice(0, 97)}…` : line;
}
